// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `exchange`

/// Send one protobuf request on a TLS-verified QUIC stream.
/// JSON is only used across the Dart/Rust bridge, never on the network.
Future<String> serverRequest({
  required String address,
  required String serverName,
  required String caPem,
  required String requestJson,
}) => RustLib.instance.api.crateApiServerServerRequest(
  address: address,
  serverName: serverName,
  caPem: caPem,
  requestJson: requestJson,
);
