import 'package:fluent_ui/fluent_ui.dart' as fluent;
import 'package:flutter/cupertino.dart' as cupertino;
import 'package:flutter/material.dart' as material;
import 'package:flutter/widgets.dart';
import 'package:saviour/providers/app_platform_provider.dart';

enum PlatformIconKind {
  back,
  forward,
  menu,
  search,
  add,
  close,
  darkMode,
  lightMode,
  language,
  device,
  lock,
  shield,
  edit,
  delete,
  email,
  phone,
  person,
  store,
  check,
  chevronDown,
  info,
}

IconData platformIcon(AppPlatform platform, PlatformIconKind kind) {
  return switch (platform) {
    AppPlatform.ios || AppPlatform.macos => switch (kind) {
      PlatformIconKind.back => cupertino.CupertinoIcons.back,
      PlatformIconKind.forward => cupertino.CupertinoIcons.forward,
      PlatformIconKind.menu => cupertino.CupertinoIcons.line_horizontal_3,
      PlatformIconKind.search => cupertino.CupertinoIcons.search,
      PlatformIconKind.add => cupertino.CupertinoIcons.add,
      PlatformIconKind.close => cupertino.CupertinoIcons.clear,
      PlatformIconKind.darkMode => cupertino.CupertinoIcons.moon_fill,
      PlatformIconKind.lightMode => cupertino.CupertinoIcons.sun_max_fill,
      PlatformIconKind.language => cupertino.CupertinoIcons.globe,
      PlatformIconKind.device => cupertino.CupertinoIcons.device_phone_portrait,
      PlatformIconKind.lock => cupertino.CupertinoIcons.lock,
      PlatformIconKind.shield => cupertino.CupertinoIcons.shield,
      PlatformIconKind.edit => cupertino.CupertinoIcons.pencil,
      PlatformIconKind.delete => cupertino.CupertinoIcons.delete,
      PlatformIconKind.email => cupertino.CupertinoIcons.mail,
      PlatformIconKind.phone => cupertino.CupertinoIcons.phone,
      PlatformIconKind.person => cupertino.CupertinoIcons.person,
      PlatformIconKind.store => cupertino.CupertinoIcons.bag,
      PlatformIconKind.check => cupertino.CupertinoIcons.check_mark,
      PlatformIconKind.chevronDown => cupertino.CupertinoIcons.chevron_down,
      PlatformIconKind.info => cupertino.CupertinoIcons.info,
    },
    AppPlatform.windows => switch (kind) {
      PlatformIconKind.back => fluent.FluentIcons.back,
      PlatformIconKind.forward => fluent.FluentIcons.forward,
      PlatformIconKind.menu => fluent.FluentIcons.global_nav_button,
      PlatformIconKind.search => fluent.FluentIcons.search,
      PlatformIconKind.add => fluent.FluentIcons.add,
      PlatformIconKind.close => fluent.FluentIcons.chrome_close,
      PlatformIconKind.darkMode => fluent.FluentIcons.clear_night,
      PlatformIconKind.lightMode => fluent.FluentIcons.sunny,
      PlatformIconKind.language => fluent.FluentIcons.locale_language,
      PlatformIconKind.device => fluent.FluentIcons.cell_phone,
      PlatformIconKind.lock => fluent.FluentIcons.lock,
      PlatformIconKind.shield => fluent.FluentIcons.shield,
      PlatformIconKind.edit => fluent.FluentIcons.edit,
      PlatformIconKind.delete => fluent.FluentIcons.delete,
      PlatformIconKind.email => fluent.FluentIcons.mail,
      PlatformIconKind.phone => fluent.FluentIcons.phone,
      PlatformIconKind.person => fluent.FluentIcons.contact,
      PlatformIconKind.store => fluent.FluentIcons.shop,
      PlatformIconKind.check => fluent.FluentIcons.check_mark,
      PlatformIconKind.chevronDown => fluent.FluentIcons.chevron_down,
      PlatformIconKind.info => fluent.FluentIcons.info,
    },
    AppPlatform.android ||
    AppPlatform.linux ||
    AppPlatform.web ||
    AppPlatform.fuchsia => switch (kind) {
      PlatformIconKind.back => material.Icons.arrow_back_rounded,
      PlatformIconKind.forward => material.Icons.arrow_forward_rounded,
      PlatformIconKind.menu => material.Icons.menu,
      PlatformIconKind.search => material.Icons.search,
      PlatformIconKind.add => material.Icons.add,
      PlatformIconKind.close => material.Icons.close,
      PlatformIconKind.darkMode => material.Icons.dark_mode_rounded,
      PlatformIconKind.lightMode => material.Icons.light_mode_rounded,
      PlatformIconKind.language => material.Icons.translate_rounded,
      PlatformIconKind.device => material.Icons.phone_iphone,
      PlatformIconKind.lock => material.Icons.lock_outline,
      PlatformIconKind.shield => material.Icons.shield_outlined,
      PlatformIconKind.edit => material.Icons.edit_outlined,
      PlatformIconKind.delete => material.Icons.delete_outline,
      PlatformIconKind.email => material.Icons.email_outlined,
      PlatformIconKind.phone => material.Icons.phone_outlined,
      PlatformIconKind.person => material.Icons.person_outline,
      PlatformIconKind.store => material.Icons.storefront_rounded,
      PlatformIconKind.check => material.Icons.check_rounded,
      PlatformIconKind.chevronDown => material.Icons.keyboard_arrow_down,
      PlatformIconKind.info => material.Icons.info_outline,
    },
  };
}
